### ISSUE TITLE
self.mail.select()  # ken add 2022-1-17 fix ubuntu use this 

### ISSUE THREAD

**Issue by ken6317461024** [thevickypedia/gmail-connector#2]
err show:
    raise self.error("command %s illegal in state %s, "
imaplib.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED

file on==>>
/.env/lib/python3.8/site-packages/gmailconnector/sms_deleter.py", line 49, in delete_sent

ogin:
        self.mail.list()
        self.mail.select('"[Gmail]/Sent Mail"')

now:
        self.mail.list()
        self.mail.select('"[Gmail]/Sent Mail"')
        self.mail.select()  # ken add 2022-1-17 fix ubuntu use this

**Comment by ken6317461024** [comment]
err 2  --Temporary failure in name resolution – Ubuntu 

# fix on ubuntu
# 1 -- do the
# Edit this file /etc/systemd/resolved.conf  < sudo nano  /etc/systemd/resolved.conf >
#   DNS=8.8.8.8  #***Enter the IP of your DNS Serer
#  2 -- do the
# Restart the resolved service
#   service systemd-resolved restart

**Comment by thevickypedia** [comment]
Thanks for raising the issue, I don't have an Ubuntu machine to check the issue.
Can you please raise a PR fixing the issue?

**Comment by thevickypedia** [comment]
I tested this on Ubuntu and it works as it is without any issue.
