### ISSUE TITLE
Installation not properly explained

### ISSUE THREAD

**Issue by lhost25** [thevickypedia/gmail-connector#6]
Thanks for this great software but unfortunately its not clear on how to make this sms work. I created .env file in "/gmail-connector" and have gmail user and pass in the file. I created a file name sendSMS.py in the same folder with .env and input send SMS script in it.

What i dont understand is where to create a custom file (env_file). Kindly please guide me through because i don't understand which python file to run and which area .env should be located. @thevickypedia 

Thanks.

<img width="1024" alt="Screenshot 2023-10-28 at 1 10 29 PM" src="https://github.com/thevickypedia/gmail-connector/assets/87344213/7f9eb16e-fe6d-4325-a888-f6b67d13d708">

<img width="1024" alt="Screenshot 2023-10-28 at 1 10 06 PM" src="https://github.com/thevickypedia/gmail-connector/assets/87344213/94c610f3-f7c2-44a9-92ad-560c99a42e37">

**Comment by thevickypedia** [comment]
@lhost25 If you already have a `.env` file in current working directory, you don't need the `custom_env`
The `custom_env` is mentioned in the docs if you name your env variables' source file as anything other than `.env`

With that being said, `gmail_user` and `gmail_pass` are the only mandatory args to startup
Once you have those values in your `.env` file, a little something like the following code is all you will need

```python
import gmailconnector as gc

messenger = gc.SendSMS()
response = messenger.send_sms(
    message="Hello-World",
    phone="1234567890",
    country_code="+1",
    subject="Test SMS",
    sms_gateway=gc.SMSGateway.tmobile
)
print(response.json())
```

The most crucial part about sending SMS is using the right SMS Gateway, I use `t-mobile` so I know their SMS Gateway, the values for `att`, `boost`, `cricket`, `uscellular` and `verizon` were the ones provided in public websites (may or may not be correct)

So you can either lookup your carrier's website to figure that out or call the customer service to get the right hostname and pass that as `sms_gateway` argument
I hope this helps, let me know if you have any further questions

**Comment by lhost25** [comment]
> @lhost25 If you already have a `.env` file in current working directory, you don't need the `custom_env` The `custom_env` is mentioned in the docs if you name your env variables' source file as anything other than `.env`
> 
> With that being said, `gmail_user` and `gmail_pass` are the only mandatory args to startup Once you have those values in your `.env` file, a little something like the following code is all you will need
> 
> ```shell
> pip freeze | grep gmail-connector  # verify if version is 1.0
> pip install --no-cache --upgrade gmail-connector
> ```
> 
> ```python
> import gmailconnector as gc
> 
> print(gc.version)  # you can also verify the version directly from the lib
> 
> messenger = gc.SendSMS()
> response = messenger.send_sms(
>     message="Hello-World",
>     phone="1234567890",
>     country_code="+1",
>     subject="Test SMS",
>     sms_gateway=gc.SMSGateway.tmobile
> )
> print(response.json())
> ```
> 
> The most crucial part about sending SMS is using the right SMS Gateway, I use `t-mobile` so I know their SMS Gateway, the values for `att`, `boost`, `cricket`, `uscellular` and `verizon` were the ones provided in public websites (may or may not be correct)
> 
> So you can either lookup your carrier's website to figure that out or call the customer service to get the right hostname and pass that as `sms_gateway` argument I hope this helps, let me know if you have any further questions

Thanks for your response and your assistant but unfortunately i still not getting it right. Firstly i have below command in my .env file in [gmailconnector](https://github.com/thevickypedia/gmail-connector/tree/main/gmailconnector) folder.

GMAIL_USER='username@gmail.com',
GMAIL_PASS='<ACCOUNT_PASSWORD>'

which file and which folder will i have this script?

import gmailconnector as gc

print(gc.version)  # you can also verify the version directly from the lib

messenger = gc.SendSMS()
response = messenger.send_sms(
    message="Hello-World",
    phone="1234567890",
    country_code="+1",
    subject="Test SMS",
    sms_gateway=gc.SMSGateway.tmobile
)
print(response.json())

and how do i run the program or which file will i run to start the program? I hope my questions are clear?

Thanks a lot.

**Comment by thevickypedia** [comment]
> Firstly i have below command in my .env file in [gmailconnector](https://github.com/thevickypedia/gmail-connector/tree/main/gmailconnector) folder.
I don't know how familiar you are with pypi libraries
`gmail-connector` is a pypi installable. So, you don't have to clone this repo or have to do anything with it.
So all you'll need is to run `pip install gmail-connector` and then import the package in project you need

**Comment by lhost25** [comment]
Well, i am familiar with pypi libraries but what i am saying is the process to run your file to work on linux is not clear.
You need to do better by walking people through to those that might not have much idea. Just give proper details so your application can help a lot people that might want to use it.

I found more suitable one already. thank you anyway.

**Comment by thevickypedia** [comment]
Thanks for your feedback. I'm sorry to hear that the documentation wasn't enough.
Glad you found a different library that suits your needs.
In the spirit of enhancing clarity, please free to provide specific details on the challenges you faced or raise a PR to address any gaps in the documentation.
